src/main/java/br/com/ordemdeev/quizzes/web/AlternativaBean.java
package br.com.ordemdeev.quizzes.web;

import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;

import br.com.ordemdeev.quizzes.alternativa.Alternativa;
import br.com.ordemdeev.quizzes.alternativa.AlternativaRN;
import br.com.ordemdeev.quizzes.pergunta.Pergunta;

@ManagedBean(name="alternativaBean")
@RequestScoped
public class AlternativaBean {
	
	private Pergunta pergunta;
	private Alternativa alternativaCadastro = new Alternativa();
	List<Alternativa> lista = null;
	
	
	@ManagedProperty(value = "#{contextoBean}")
	private ContextoBean contextoBean;
	
	
	public String salvar()
	{
		String mensagemValidacao = new String();
		
		if(alternativaCadastro.getDescricao().equals(""))
		{
			mensagemValidacao = "Alternativa inválida\n";
		}
		
		
		if(!mensagemValidacao.equals(""))
		{
			FacesContext context = FacesContext.getCurrentInstance();
			FacesMessage facesMessage = new FacesMessage(mensagemValidacao);
			context.addMessage(null, facesMessage);
			return null;
		}
		
		if(alternativaCadastro.getCodigo() == null || alternativaCadastro.getCodigo() == 0)
		{
			alternativaCadastro.setPergunta(this.getContextoBean().getPerguntaAtiva());
		}
		
		AlternativaRN alternativaRN = new AlternativaRN();
		alternativaRN.salvar(alternativaCadastro);
		
		alternativaCadastro = null;
		lista = null;
		return null;
	}
	
	public String excluir()
	{
	    AlternativaRN alternativaRN = new AlternativaRN();
	    alternativaRN.excluir(alternativaCadastro);
	    
	    alternativaCadastro = null;
	    lista = null;
	    return null;
	}
	

	public Pergunta getPergunta() {
		
		if(pergunta == null)
		{
			pergunta = contextoBean.getPerguntaAtiva();
		}
		
		return pergunta;
	}
	
	public List<Alternativa> getLista() {
		
		if(lista == null)
		{
			AlternativaRN alternativaRN = new AlternativaRN();
			lista = alternativaRN.listar(this.contextoBean.getPerguntaAtiva());
		}
		
		return lista;
	}

	public void setLista(List<Alternativa> lista) {
		this.lista = lista;
	}
	

	public Alternativa getAlternativaCadastro() {
		return alternativaCadastro;
	}

	public void setAlternativaCadastro(Alternativa alternativaCadastro) {
		this.alternativaCadastro = alternativaCadastro;
	}

	public void setPergunta(Pergunta pergunta) {
		this.pergunta = pergunta;
	}

	public ContextoBean getContextoBean() {
		return contextoBean;
	}

	public void setContextoBean(ContextoBean contextoBean) {
		this.contextoBean = contextoBean;
	}
	
	
	
	
	
	

}

src/main/java/br/com/ordemdeev/quizzes/web/ContextoBean.java
package br.com.ordemdeev.quizzes.web;

import java.io.Serializable;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import br.com.ordemdeev.quizzes.grupo.Grupo;
import br.com.ordemdeev.quizzes.pergunta.Pergunta;
import br.com.ordemdeev.quizzes.pergunta.PerguntaRN;
import br.com.ordemdeev.quizzes.usuario.Usuario;
import br.com.ordemdeev.quizzes.usuario.UsuarioRN;


@ManagedBean
@SessionScoped
public class ContextoBean implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -8803396238050792504L;
	
	private Grupo grupoAtivo;
	private Pergunta perguntaAtiva;
	private List<Pergunta> perguntasResponder;
	private int numeroPergunta;
	
	
	public Usuario getUsuarioLogado()
	{
		FacesContext context = FacesContext.getCurrentInstance();
		ExternalContext external = context.getExternalContext();
		String login = external.getRemoteUser();
		if(login != null)
		{
			UsuarioRN usuarioRN = new UsuarioRN();
			return usuarioRN.buscarPorLogin(login);
		}
		return null;
	}
	
	public Pergunta retornaPerguntaLista()
	{
		if(numeroPergunta < getPerguntasResponder().size())
		{
			perguntaAtiva = getPerguntasResponder().get(numeroPergunta);
			return perguntaAtiva;
		}
		
		return null;
	}

	public Grupo getGrupoAtivo() {
		return grupoAtivo;
	}

	public void setGrupoAtivo(Grupo grupoAtivo) {
		this.grupoAtivo = grupoAtivo;
	}

	public Pergunta getPerguntaAtiva() {
		return perguntaAtiva;
	}

	public void setPerguntaAtiva(Pergunta perguntaAtiva) {
		this.perguntaAtiva = perguntaAtiva;
	}

	public List<Pergunta> getPerguntasResponder() {
		
		PerguntaRN perguntaRN = new PerguntaRN();
	    perguntasResponder = perguntaRN.listar(getGrupoAtivo());
		
		
		return perguntasResponder;
	}

	public void setPerguntasResponder(List<Pergunta> perguntasResponder) {
		this.perguntasResponder = perguntasResponder;
	}

	public int getNumeroPergunta() {
		return numeroPergunta;
	}

	public void setNumeroPergunta(int numeroPergunta) {
		this.numeroPergunta = numeroPergunta;
	}
	
	
	

}

src/main/java/br/com/ordemdeev/quizzes/web/HomeBean.java
package br.com.ordemdeev.quizzes.web;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;

@ManagedBean(name="homeBean")
@RequestScoped
public class HomeBean {
	
	@ManagedProperty(value = "#{contextoBean}")
	private ContextoBean contextoBean;
	
	
	public String responderQuestionario()
	{
		contextoBean.setNumeroPergunta(0);
		contextoBean.setPerguntasResponder(null);
		return "consultaGrupos";
	}
	
	public String getNomeUsuario()
	{
		return this.contextoBean.getUsuarioLogado().getNome();
	}


	public ContextoBean getContextoBean() {
		return contextoBean;
	}


	public void setContextoBean(ContextoBean contextoBean) {
		this.contextoBean = contextoBean;
	}
	
	
	

}

src/main/java/br/com/ordemdeev/quizzes/web/PerguntasBean.java
package br.com.ordemdeev.quizzes.web;

import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;

import br.com.ordemdeev.quizzes.grupo.Grupo;
import br.com.ordemdeev.quizzes.pergunta.Pergunta;
import br.com.ordemdeev.quizzes.pergunta.PerguntaRN;

@ManagedBean(name = "PerguntasBean")
@RequestScoped
public class PerguntasBean {
	
	private Grupo grupo;
	private Pergunta perguntaCadastro = new Pergunta();
	private List<Pergunta> lista = null;
	
	@ManagedProperty(value = "#{contextoBean}")
	private ContextoBean contextoBean;
	
	public String salvar()
	{
		if(perguntaCadastro.getDescricao().equals(""))
		{
			FacesContext context = FacesContext.getCurrentInstance();
			FacesMessage facesMessage = new FacesMessage("Questão inválida");
			context.addMessage(null, facesMessage);
			return null;
		}
		
		perguntaCadastro.setGrupo(this.getGrupo());
		PerguntaRN perguntaRN = new PerguntaRN();
		perguntaRN.salvar(perguntaCadastro);
		
		lista = null;
		perguntaCadastro = null;
		return null;
		
	}
	
	public String abrirCadastroDeAlternativas()
	{
		this.contextoBean.setPerguntaAtiva(perguntaCadastro);
		return "alternativas";
	}
	
	public String excluir()
	{
		PerguntaRN perguntaRN = new PerguntaRN();
		perguntaRN.excluir(perguntaCadastro);
		
		perguntaCadastro = null;
		lista = null;
		return null;
	}
	
	public Grupo getGrupo() {
		
		if(this.grupo == null)
		{
			this.grupo = contextoBean.getGrupoAtivo();
		}
		
		return grupo;
	}
	
	public List<Pergunta> getLista() {
		
		if(lista == null)
		{
			PerguntaRN perguntaRN = new PerguntaRN();
			lista = perguntaRN.listar(this.getGrupo());
		}
		
		return lista;
	}
	
	public void setLista(List<Pergunta> lista) {
		this.lista = lista;
	}
	
	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}


	public Pergunta getPerguntaCadastro() {
		return perguntaCadastro;
	}
	
	
	public void setPerguntaCadastro(Pergunta perguntaCadastro) {
		this.perguntaCadastro = perguntaCadastro;
	}


	public ContextoBean getContextoBean() {
		return contextoBean;
	}

	public void setContextoBean(ContextoBean contextoBean) {
		this.contextoBean = contextoBean;
	}
	
	
	
	

}

src/main/java/br/com/ordemdeev/quizzes/web/RankingBean.java
package br.com.ordemdeev.quizzes.web;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;

import br.com.ordemdeev.quizzes.alternativa.Alternativa;
import br.com.ordemdeev.quizzes.alternativa.AlternativaRN;
import br.com.ordemdeev.quizzes.usuario.Usuario;
import br.com.ordemdeev.quizzes.usuario.UsuarioRN;
import br.com.ordemdeev.quizzes.web.classesUteis.RankingUtil;

@ManagedBean(name = "rankingBean")
@RequestScoped
public class RankingBean {
	
	List<Usuario> usuarios = null;
	List<RankingUtil> listaUsuarios = null;
	
	@ManagedProperty(value = "#{contextoBean}")
	private ContextoBean contextoBean;
	
	public List<Usuario> getUsuarios() {
		
		if(usuarios == null)
		{
			UsuarioRN usuarioRN = new UsuarioRN();
			usuarios = usuarioRN.listar();
		}
		
		return usuarios;
	}

	public void setUsuarios(List<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	public ContextoBean getContextoBean() {
		return contextoBean;
	}

	public void setContextoBean(ContextoBean contextoBean) {
		this.contextoBean = contextoBean;
	}

	public List<RankingUtil> getListaUsuarios() {
		
		if(listaUsuarios == null)
		{
			listaUsuarios = new ArrayList<RankingUtil>();
			usuarios = this.getUsuarios();
			List<Alternativa> alternativasSelecionadas;
			AlternativaRN alternativaRN = new AlternativaRN();
			for(int i = 0; i < usuarios.size(); i++)
			{
				alternativasSelecionadas = alternativaRN.buscarAlternativasUsuario(usuarios.get(i), contextoBean.getGrupoAtivo());
				if(alternativasSelecionadas != null)
				{
					double somatorio = 0;
					for(int j=0; j < alternativasSelecionadas.size(); j++)
					{
						somatorio += alternativasSelecionadas.get(j).getPontos();
					}
				
					if(somatorio > 0)
					{
						RankingUtil usuarioParaRanking = new RankingUtil(usuarios.get(i), somatorio);
						listaUsuarios.add(usuarioParaRanking);
					}
				}
			}
		
			if(listaUsuarios != null)
			{
				if(!listaUsuarios.isEmpty())
				{
					Collections.sort(listaUsuarios);
				}
			}
		}
		
		return listaUsuarios;
	}

	public void setListaUsuarios(List<RankingUtil> listaUsuarios) {
		this.listaUsuarios = listaUsuarios;
	}
	
	
	

}

src/main/java/br/com/ordemdeev/quizzes/web/ResponderBean.java
package br.com.ordemdeev.quizzes.web;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;

import br.com.ordemdeev.quizzes.alternativa.Alternativa;
import br.com.ordemdeev.quizzes.alternativa.AlternativaRN;
import br.com.ordemdeev.quizzes.grupo.Grupo;
import br.com.ordemdeev.quizzes.pergunta.Pergunta;
import br.com.ordemdeev.quizzes.usuario.Usuario;
import br.com.ordemdeev.quizzes.usuario.UsuarioRN;

@ManagedBean(name = "responderBean")
@RequestScoped
public class ResponderBean {
	
	private Grupo grupo = null;
	private Pergunta pergunta = null;
	private Alternativa alternativa = new Alternativa();
	private List<Alternativa> alternativas;
	
	@ManagedProperty(value = "#{contextoBean}")
	private ContextoBean contextoBean;
	
	
	public String salvareCarregarProxima()
	{
		
		
		if(alternativa == null)
		{
			return null;
		}
		
		if(alternativa.getCodigo() != null)
		{
			Usuario usuario = contextoBean.getUsuarioLogado();
			usuario.getRespostas().add(alternativa);
			
			UsuarioRN usuarioRN = new UsuarioRN();
			usuarioRN.salvar(usuario);
		}
		
		
		contextoBean.setNumeroPergunta(contextoBean.getNumeroPergunta()+1);
		if(contextoBean.getNumeroPergunta() >= contextoBean.getPerguntasResponder().size())
		{
			if(alternativa.getCodigo() == null && contextoBean.getNumeroPergunta() == 1)
			{
				contextoBean.setNumeroPergunta(0);
				contextoBean.setPerguntasResponder(null);
				return "home";
			}
			
			contextoBean.setNumeroPergunta(0);
			contextoBean.setPerguntasResponder(null);
			return "pontuacaoResposta";
		}
		
		alternativa = null;
		alternativas = null;
		pergunta = null;
		return null;
	}
	
	

	public Grupo getGrupo() {
		
		if(grupo == null)
		{
			grupo = this.contextoBean.getGrupoAtivo();
		}
		
		return grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	public Alternativa getAlternativa() {
		return alternativa;
	}

	public void setAlternativa(Alternativa alternativa) {
		this.alternativa = alternativa;
	}

	public ContextoBean getContextoBean() {
		return contextoBean;
	}

	public void setContextoBean(ContextoBean contextoBean) {
		this.contextoBean = contextoBean;
	}

	public List<Alternativa> getAlternativas() {
		
		if(alternativas == null)
		{
			AlternativaRN alternativaRN = new AlternativaRN();
			alternativas = alternativaRN.listar(this.contextoBean.getPerguntaAtiva());
			
			UsuarioRN usuarioRN = new UsuarioRN();
			usuarioRN.removerPerguntasRespondidas(contextoBean.getUsuarioLogado(), alternativas);
			
		}
		
		return alternativas;
	}

	public void setAlternativas(List<Alternativa> alternativas) {
		this.alternativas = alternativas;
	}

	public Pergunta getPergunta() {
		
		if(pergunta == null)
		{
			pergunta = contextoBean.retornaPerguntaLista();
		}
		
		return pergunta;
	}

	public void setPergunta(Pergunta pergunta) {
		this.pergunta = pergunta;
	}
	
	
	

}

src/main/webapp/restrito/ResponderPerguntas.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
    <title>Quizzes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="#{request.contextPath}/resources/bootstrap/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="#{request.contextPath}/resources/css/estilo_01.css"/>
</h:head>
<h:body>
    <h:form>

        <div class="container padding_geral">
            <div class="row">
                <div class="col-sm-12">
                    <h3>Responder Perguntas</h3><h:commandButton styleClass="btn btn-outline-success btn-sm" value="Voltar" action="home"></h:commandButton>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <h3>1 - Descrição da pergunta</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2">
                    <h:selectOneRadio >
                        <f:selectItem itemValue="Red" itemLabel="a" />
                    </h:selectOneRadio>
                </div>
            </div>
        </div>

    </h:form>
</h:body>
</html>

src/main/webapp/restrito/alternativas.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<link rel="stylesheet" href="#{request.contextPath}/resources/bootstrap/css/bootstrap.min.css"/>
	 <link rel="stylesheet" href="#{request.contextPath}/resources/css/estilo_01.css"/>
	<title>Cadastro Grupo de Perguntas</title>
</h:head>
<h:body>
	<div class="container">
	<h:form id="edicao">

	<h4 class="text-center"><h:outputText value="#{alternativaBean.pergunta.descricao}" /><h:commandLink value="voltar" action="perguntas" styleClass="btn btn-outline-success btn-sm" /></h4>
	<hr/>
		<h:messages />
		<h:inputHidden value="#{alternativaBean.alternativaCadastro.codigo}" />
		<div class="col-sm-12">
			<div class="row">
				<label>Alternativa</label>
				<h:inputText label="Alternativa" value="#{alternativaBean.alternativaCadastro.descricao}" styleClass="form-control"/>
				<label>Valor</label>
				<h:inputText label="Valor" value="#{alternativaBean.alternativaCadastro.pontos}" styleClass="form-control"/>
			</div>
		</div>

		<h:commandButton action="#{alternativaBean.salvar}" value="Salvar" styleClass="btn btn-success"/>
	</h:form>

		<div class="col-sm-12">
			<div class="row">
				<h4>Cadastros já realizados</h4>
				<hr/>
			</div>
		</div>

	<h:form id="listagem">
		<div class="col-sm-12">
			<div class="row">
			<h:dataTable value="#{alternativaBean.lista}" var="lista" rendered="#{not empty alternativaBean.lista}" styleClass="table table-striped" style="width: 100%;">
			<h:column>
				<f:facet name="header">Alternativa</f:facet>
					<h:outputText value="#{lista.descricao}"/>
			</h:column>
			<h:column>
				<f:facet name="header">Valor</f:facet>
					<h:outputText value="#{lista.pontos}"/>
			</h:column>
			<h:column>
				<h:commandLink value="Editar" styleClass="btn btn-info btn-sm btn-block">
				<f:ajax execute="@this" render=":edicao"/>
				 <f:setPropertyActionListener value="#{lista}" target="#{alternativaBean.alternativaCadastro}" />
				</h:commandLink>
			</h:column>
			<h:column>
				<h:commandLink value="Excuir" action="#{alternativaBean.excluir}" styleClass="btn btn-danger btn-sm btn-block">
				<f:ajax execute="@this" render=":listagem" />
				<f:setPropertyActionListener value="#{lista}" target="#{alternativaBean.alternativaCadastro}" />
				</h:commandLink>
			</h:column>
			</h:dataTable>
			</div>
		</div>
</h:form>
	</div>
</h:body>
</html>

src/main/webapp/restrito/grupoCadastro.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<link rel="stylesheet" href="#{request.contextPath}/resources/bootstrap/css/bootstrap.min.css"/>
	 <link rel="stylesheet" href="#{request.contextPath}/resources/css/estilo_01.css"/>
	<title>Cadastro Questionários</title>
</h:head>
<h:body>
	<div class="container">
	<h:form id="edicao">

	<h4 class="text-center">Cadastro Questionários<h:commandLink value="voltar" action="home" styleClass="btn btn-outline-success btn-sm" /></h4>
	<hr/>
		<h:messages />
		<h:inputHidden value="#{grupoBean.grupoCadastro.codigo}" />
		
		<div class="col-sm-12">
			<div class="row">
				<label>Titulo</label>
				<h:inputText label="Nome" value="#{grupoBean.grupoCadastro.titulo}" styleClass="form-control"/>
				<label>Descrição</label>
				<h:inputText label="Descricao" value="#{grupoBean.grupoCadastro.descricao}" styleClass="form-control"/>
			</div>
		</div>

		<h:commandButton action="#{grupoBean.salvar}" value="Salvar" styleClass="btn btn-success"/>
	</h:form>

		<div class="col-sm-12">
			<div class="row">
				<h4>Cadastros já realizados</h4>
				<hr/>
			</div>
		</div>

	<h:form id="listagem">
		<div class="col-sm-12">
			<div class="row">
			<h:dataTable value="#{grupoBean.lista}" var="lista" rendered="#{not empty grupoBean.lista}" styleClass="table table-striped" style="width: 100%;">
			<h:column>
				<f:facet name="header">Título</f:facet>
					#{lista.titulo}
			</h:column>
			<h:column>
				<f:facet name="header">Descricao</f:facet>
					<h:outputText value="#{lista.descricao}"/>
			</h:column>
			<h:column>
				<f:facet name="header">Dono</f:facet>
				<h:outputText value="#{lista.usuario.nome}"/>
			</h:column>
			<h:column>
				<h:commandLink value="Editar" styleClass="btn btn-info btn-sm btn-block">
				<f:ajax execute="@this" render=":edicao"/>
				 <f:setPropertyActionListener value="#{lista}" target="#{grupoBean.grupoCadastro}" />
				</h:commandLink>
			</h:column>
			<h:column>
				<h:commandLink value="Excuir" action="#{grupoBean.excluir}" styleClass="btn btn-danger btn-sm btn-block">
				<f:ajax execute="@this" render=":listagem" />
				<f:setPropertyActionListener value="#{lista}" target="#{grupoBean.grupoCadastro}"/>
				</h:commandLink>
			</h:column>
			<h:column>
				<h:commandLink value="Cadastrar / Alterar Perguntas" action="#{grupoBean.abrirCadastroDePerguntas}" styleClass="btn btn-warning btn-sm btn-block">
				<f:setPropertyActionListener value="#{lista}" target="#{grupoBean.grupoCadastro}" />
				</h:commandLink>
			</h:column>
			</h:dataTable>
			</div>
		</div>
</h:form>
	</div>
</h:body>
</html>

src/main/webapp/restrito/home.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
	<title>Quizzes</title>
	 <meta name="viewport" content="width=device-width, initial-scale=1" />
	 <link rel="stylesheet" href="#{request.contextPath}/resources/bootstrap/css/bootstrap.min.css"/>
	 <link rel="stylesheet" href="#{request.contextPath}/resources/css/estilo_01.css"/>
</h:head>
<h:body>
	<h:form>

		<div class="container padding_geral">
			<div class="row">
				<div class="col-sm-12">
					<h3>Selecione uma opção</h3>
				</div>
			</div>
			<div class="row margem_title_superior">
				<div class="col-sm-12">
				<h:outputText value="Bem vindo #{homeBean.nomeUsuario} " />
					<a onclick="document.location='#{request.contextPath}/j_spring_security_logout'" class="btn btn-outline-success btn-sm">sair</a>
				</div>
			</div>
			<div class="row margem_botao">
				<div class="col-sm-12">
					<h:commandButton styleClass="btn btn-default btn-block" value="Criar/Editar Questionários" action="grupoCadastro"></h:commandButton>
					<h:commandButton styleClass="btn btn-default btn-block" value="Responder Questionários" action="grupoResponder"></h:commandButton>
					<h:commandButton styleClass="btn btn-default btn-block" value="Consultar Ranking Questionários" action="rankingGrupos"></h:commandButton>
				</div>
			</div>
		</div>
	</h:form>
	</h:body>
</html>

src/main/webapp/restrito/pontuacaoResposta.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<link rel="stylesheet" href="#{request.contextPath}/resources/bootstrap/css/bootstrap.min.css"/>
	 <link rel="stylesheet" href="#{request.contextPath}/resources/css/estilo_01.css"/>
	<title>Pontuação resposta</title>
</h:head>
<h:body>
	<div class="container">
	<h:form id="listagem">
	<h4 class="text-center"><h:outputText value="Mostrar Pontuação do Questionário" /><h:commandLink value="Tela Inicial" action="home" styleClass="btn btn-outline-success btn-sm" /></h4>
	<h:outputLabel value="#{contextoBean.usuarioLogado.nome} Sua Pontuação foi de #{pontuacaoBean.somatorioQuestionario}"/><br/>
	<h:outputLabel value="Alternativas escolhidas"/>
		<div class="col-sm-12">
			<div class="row">
			<h:dataTable value="#{pontuacaoBean.alternativasSelecionadas}" var="lista" rendered="#{not empty pontuacaoBean.alternativasSelecionadas}" styleClass="table table-striped" style="width: 100%;">
			<h:column>
				<f:facet name="header">Respostas</f:facet>
					<h:outputText value="#{lista.descricao}"/>
			</h:column>
			<h:column>
				<f:facet name="header">Quantidade de Pontos</f:facet>
					<h:outputText value="#{lista.pontos}"/>
			</h:column>
			</h:dataTable>
			</div>
		</div>
</h:form>
	</div>
</h:body>
</html>